### ISSUE TITLE
Edit bar cover Button of preview result

### ISSUE THREAD

**Issue by chinanf-boy** [ory/editor#397]
![pic-cover 2017-05-29 10 47 26](https://cloud.githubusercontent.com/assets/20272484/26535138/261613d0-445d-11e7-8f2e-291fac6f660a.jpg)

# when the Edit bar show,
#  cover most of the Button of preview result area

**Comment by arekkas** [comment]
Thanks for the report! Probably something that can be solved easily with z-index

**Comment by simonkaspersen** [comment]
Hi!
Will the **edit bar** in some scenario take up the whole bottom of the page? In that case maybe check for size and push the whole **button-bar** up above the **edit-bar**?
If it is interesting I can take a look at it

**Comment by arekkas** [comment]
we limited the edit bar to a maximum width of 80% i think which should not collide with the sidebar on the right. however there were people who said that they dislike the long "travel times" you need to do with the mouse in order to edit rich text. maybe we'll show it simply in place of the cursor? what do you think?

**Comment by simonkaspersen** [comment]
I can see that, especially on bigger screens.
 
What do you mean by having it in place of the cursor? That the **edit-bar** has a relationship with each element instead of being fixed on bottom?

I think that if the whole bare is following the cursor or current position of the marker, it would maybe move a lot, but I think if it is stationary close to each active element, it would be perfect.

I also would consider not to have the **button-bar** fixed i bottom-right corner, it is far away from the editor on larger screens. Maybe have fixed on in the middel just besides the page that are edited?

What do you think?
