### ISSUE TITLE
Cannot have two HTML5 backends at the same time

### ISSUE THREAD

**Issue by Exin** [ory/editor#424]
I'm trying to use my own component that has` react-dnd` as a dependency, and meanwhile, I also use `ory-editor` as the rich-text editor in my app. In this case, there are two HTML5 backends at the same time and I got the problem. Maybe I need to define `DragDropContext` on common parent of my own component  and` ory-editor`, but how can I get the ory-editor without `DragDropContext`? What would be the best way to fix this?

**Comment by arekkas** [comment]
The best way to fix this would be to pass the backend via the config array during instantiation, and if nothing is passed, use the htmlbackend as default. This is currently not supported and would require a PR. The soonest I can look at it is in 3-4 weeks unfortunately. :(

**Comment by benoj** [comment]
+1 for this also

**Comment by nqthuan303** [comment]
how can i pass the backend via config? can you please give me an example? thanks

**Comment by arekkas** [comment]
Pass it to `new Editor`: https://github.com/ory/editor/blob/master/packages/core/src/index.js#L64

**Comment by MichaelDM** [comment]
Hi @arekkas, I am using Ory and React-Source-Tree in my app, and if possible, I would love a little bit more context on your solution and how to apply it, because I'm still getting the multiple backend error.
gcorne's solution makes sense to me (https://github.com/react-dnd/react-dnd/issues/186) because he's creating one instance of the dragAndDrop Context ```export default DragDropContext(HTML5Backend)``` and uses that HOC to decorate his components and pass the context. 
When I look at Ory's source code for the editor, the backend is passed to the constructor as so ```    this.dragDropContext = dragDropContext(dragDropBackend || dndBackend)```
.So this is the implementation I understand that is possible (and please let me know if I'm making a mistake). 
```export default new Editor({
  plugins: editorPlugin,
  editables: [createEmptyState()],
  dragDropBackend: HTML5Backend,
})
``` 
However, does that solve the issue? It seems to me that no matter what, we are still creating a new context for dnd? Or perhaps there is something about the backend that I pass that I'm misunderstanding (because in this example, I'm strictly repeating `dndBackend`, the fallback `dragDropBacken`). 
Thanks for your help!

**Comment by arekkas** [comment]
When you import the backend, it [creates a new instance](https://github.com/react-dnd/react-dnd/blob/master/packages/react-dnd-html5-backend/src/index.ts#L9) which is probably causing your error. Make sure you import `HTML5Backend` only once.

**Comment by bekicot** [comment]
Internally, ory-editor is importing the backend. Isn't it causing the "Cannot have two HTML5 backends at the same time" error?
Is there any other way so that we can implement reactdnd for our other feature, along with ory-editor?

**Comment by hungle1220** [comment]
I used editor with react-sortable-tree. Any suggestions?

**Comment by xuananpham93** [comment]
I have the same problem? How to resolve it?

**Comment by macrozone** [comment]
> When you import the backend, it [creates a new instance](https://github.com/react-dnd/react-dnd/blob/master/packages/react-dnd-html5-backend/src/index.ts#L9) which is probably causing your error. Make sure you import `HTML5Backend` only once.

actually, it exports a function that creates a new backend. Maybe you refering to an older version? Also the version used in ory editor looks quite old, maybe an upgrade would help?
